platform :ios, '9.3'

target 'NKDemo' do
  use_frameworks!
  inhibit_all_warnings!

  # Pods for NKDemo
  pod 'ObservableKit', '~> 1.0'
  pod 'BaseNetworkKit', :git => 'https://github.com/limadeveloper/BaseNetworkKit.git', :branch => 'master'

end